### ISSUE TITLE
PHP 7.1 support

### ISSUE THREAD

**Issue by fmunch** [nick-jones/php-ucd#1]
Hi,

Is PHP 7.1 support planned?

`void` is now a reserved word, so the [Void](https://github.com/nick-jones/php-ucd/blob/master/lib/UCD/Unicode/Character/Properties/Normalization/Decomposition/Void.php) class needs to be renamed.

Thanks for your work on this package!

**Comment by nick-jones** [comment]
Hi, thanks for raising this. I'll look to get it addressed over the weekend.

**Comment by nick-jones** [comment]
I've renamed the class and bumped the major version number, since this constitutes a BC break - [v2.0.0](https://github.com/nick-jones/php-ucd/releases/tag/v2.0.0). I've also updated various things for Unicode 10.0

**Comment by fmunch** [comment]
Thank you @nick-jones.

The folder [resources/generated/ucd](https://github.com/nick-jones/php-ucd/tree/master/resources/generated/ucd) lost almost all its files (caused by bda4f4e). Was that expected? Are we now supposed to build the database before using the lib?

**Comment by nick-jones** [comment]
My apologies, that was a silly mistake. I've pushed the missing files and retagged as [v3.0.0](https://github.com/nick-jones/php-ucd/releases/tag/v3.0.0)
